"""empty message

Revision ID: 235b3ef93c89
Revises: 095e4e9fdb4b
Create Date: 2023-01-26 17:44:21.893920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235b3ef93c89'
down_revision = '095e4e9fdb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_transaction')
    # ### end Alembic commands ###
