"""empty message

Revision ID: 42af27267e2c
Revises: 19579528138c
Create Date: 2023-02-03 11:33:40.427816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42af27267e2c'
down_revision = '19579528138c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
