"""empty message

Revision ID: 869fe712d6ab
Revises: f5c7141a913c
Create Date: 2023-01-26 16:22:21.269673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869fe712d6ab'
down_revision = 'f5c7141a913c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant')
    # ### end Alembic commands ###
